import type { Metadata } from "next";
import { Navbar } from "@/components/NavBar";
import { Footer } from "@/components/Footer";
import { SimpleToaster } from "@/components/SimpleToaster";
import { ToastProvider } from "@/hooks/use-simple-toast";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ToastProvider>
          <div className="min-h-screen flex flex-col">
            <Navbar />
            <main className="flex-1 pt-24">
              {children}
            </main>
            <Footer />
            <SimpleToaster />
          </div>
        </ToastProvider>
      </body>
    </html>
  );
}



